<?php

  $GLOBALS['conf']['cache'] = FALSE;
/**
 * Implements hook_block_info.
 */
include_once '../../../../../includes/bootstrap.inc';
drupal_bootstrap(DRUPAL_BOOTSTRAP_FULL);

function iit_multiple_display_hours_block_info() {
  $blocks['hours'] = array(
    'info' => t('IIT Multiple Display Library Hours'),
    'cache' => DRUPAL_NO_CACHE
  );
  return $blocks;
}
function iit_multiple_display_hours_get_and_format_date($daysAhead){
  $dateFormat="l, F j";
  $today = date($dateFormat,time()+($daysAhead*86400));
  return $today;
}
//retrieve JSON data from a Google Calendar (public)
function iit_multiple_display_hours_format_hours_data($dateData){// default is to use Galvin and today's Unix date
  $msg="no data available";
  $timeFormat="g:ia";
  
// error gracefully if no data
    if (count($dateData)<=0){
      return $msg;
    }
    else{
      $item = $dateData[0]; // no need to loop. just get first object
    }     
    $title = $item->summary;

    if (stripos($title,"closed")===false) { // library open (verify identical FALSE to avoid "false false")

        // Google Calendar API v3 uses the date field if event is a full day long, or the dateTime field if it is less than 24 hours  
      if (isset($item->start->dateTime)){ // non 24-hour event
          $tmpStart=strtotime(substr($item->start->dateTime, 0,16));
          $tmpEnd=strtotime(substr($item->end->dateTime, 0,16));
      }

      else{ // all day event
        $tmpStart=strtotime(substr($item->start->date, 0,16));
        $tmpEnd=strtotime(substr($item->end->date, 0,16));
      }
      
      $startTime = iit_display_hours_format_time(date($timeFormat,$tmpStart));
      $endTime = iit_display_hours_format_time(date($timeFormat,$tmpEnd));
      
      $msg=iit_display_hours_format_todays_hours($startTime, $endTime);

      return $msg; // return hours info
    } // end library open

    // library is closed
    else {
      return $title;
    }
        
}// end function
function iit_multiple_display_hours_get_calendar_data($calendar, $dayToGet=0){
  $debug=false;
  $key = getenv('GOOGLE_API'); // duritalservices@iit.edu Google API key
  if(($key==NULL)||($key=="")){
    trigger_error('Google API key not found', E_USER_NOTICE);
  }  
  $APIformat="Y-m-d";
  $timeMin = date($APIformat,time()+($dayToGet*86400)) . 'T06:00:00.000Z';
  $timeMax = date($APIformat,time()+($dayToGet*86400)) . 'T22:00:00.000Z';
  $url='https://www.googleapis.com/calendar/v3/calendars/' . $calendar . '/events?singleEvents=true&orderby=startTime&timeMin=' . 
      $timeMin . '&timeMax=' . $timeMax . '&maxResults=1&key=' . $key;
    //this works more reliably than only getting one event
    //google api pads date, was causing problems with returning yesterday's event. Instead of using midnight and 11:59 for range, use noon-1pm
  if ($debug){
    print $url . "<br/>";
  }
  $jsonFile = file_get_contents($url);
  if (!$jsonFile) {
      trigger_error('NO DATA returned from url.', E_USER_NOTICE);
  }
  else {
    // convert the string to a json object
    $jsonObj = json_decode($jsonFile);
    $dateData = $jsonObj->items;
    return $dateData;
  }
}
function iit_multiple_display_hours_format_message($incluldeOpenMsg, $daysAhead){
  $debug=false;
  $galvinCal="iit.edu_8l0d8qd4qtfn7skmgkiu55uv58%40group.calendar.google.com";
  $message="";

    $dataObj=iit_multiple_display_hours_get_calendar_data($galvinCal, $daysAhead);

    if (count($dataObj)>0){
      if ($debug){
        print_r($dataObj[0]);
      }
      $message .= iit_multiple_display_hours_format_hours_data($dataObj);
      if ($incluldeOpenMsg>0){// won't use this flag for hours page
        $isOpen = iit_multiple_display_hours_check_if_open($dataObj[0]);
        $openMsg = iit_multiple_display_hours_format_open_msg($isOpen);
        $message .= "<p>Currently: $openMsg</p>";
        //$message="";
      }
    }
    else{
      $message .= "<p>Library hours cannot be displayed at this time.</p>";
    }
  //    $message .= "<a href=\"https://www.google.com/calendar/embed?mode=week&src=iit.edu_8l0d8qd4qtfn7skmgkiu55uv58%40group.calendar.google.com&ctz=America/Chicago\"><img src=\"sites\all\modules\custom\iit_multiple_display_hours\images\google-calendar-icon-sm.png\"/></a>";

  return $message;  
  
}
function iit_multiple_display_hours_block_view($delta = '') {
  $incluldeOpenMsg=0;
  for ($i=1; $i<8; $i++){
    $day = "<div class=\"col1\">" . iit_multiple_display_hours_get_and_format_date($i) . "</div>";
    $hours = "<div class=\"col2\">" . iit_multiple_display_hours_format_message($incluldeOpenMsg, $i) . "</div>";
    $msg .= $day . $hours;
  }
//  $block['subject'] = t("Today's Hours");
  $block['content'] = $msg;
  return $block;
}
//Include shared functions
module_load_include('inc', 'libraries', 'iit_hours_functions');

// http://www.wdtutorials.com/drupal-7/drupal-7-how-to-create-module-part-1#.VV47xvlVhBc
// https://ezproxy.gl.iit.edu/login?url=http://dx.doi.org/10.1007/978-1-4302-2839-4
